name: mac-sign-2

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build HWI
        working-directory: ${{runner.workspace}}
        run: |
          brew install libusb python3 poetry
          git clone https://github.com/bitcoin-core/HWI.git
          cd HWI
          pip3 install poetry
          poetry install
          pip3 install .
          pip3 install -U setuptools
          python3 setup.py install
          echo "Installed hwi"
          find . -name "hwi"
          cd ..
          mkdir build
          cp /Library/Frameworks/Python.framework/Versions/3.11/bin/hwi ${{runner.workspace}}/build/
          find . -name "hwi"
