name: mac-build-hwi

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      
      - name: Build HWI
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          brew install libusb python3 poetry pyenv
          pyenv install 3.9.7
          wget -c -q "https://github.com/bitcoin-core/HWI/archive/refs/tags/2.2.1.zip" -O - | tar -xz
          cd HWI-2.2.1
          pip3 install poetry
          poetry install
          pip3 install .
          pip3 install -U setuptools
          #pip install pyinstaller
          #python3 setup.py install
          #pyinstaller --onefile setup.py
          sh contrib/build_bin.sh
          echo "Installed hwi"
          #cp /Library/Frameworks/Python.framework/Versions/3.11/bin/hwi ${{runner.workspace}}/build/Nunchuk.app/Contents/MacOS/
          find ${{runner.workspace}} -name "hwi"
          
          mkdir nunchuk-mac-qt
          mv /Library/Frameworks/Python.framework/Versions/3.11/bin/hwi nunchuk-mac-qt
          zip -r nunchuk-mac-qt.zip nunchuk-mac-qt
     
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Upload Artifact
        uses: 'actions/upload-artifact@v2'
        with:
          name: nunchuk-mac-${{ steps.get_version.outputs.VERSION }}
          path: ${{runner.workspace}}/build/nunchuk-mac-qt.zip
